version: "3"
services:
  mysql:
    container_name: some-mysql
    volumes:
      - dbdata:/var/lib/mysql # Persistir BBDD
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  
  prestashop:
    container_name: prestashop
    volumes:
      - psdata:/var/www/html # Persistir Prestashop
      - type: volume # Persistir imágenes
        source: psmedia
        target: /var/www/html/img
      - type: volume # Persistir traducciones
        source: pstranslations
        target: /var/www/html/translations
      - type: volume
        source: pslogs
        target: /var/log
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network

networks:
  prestashop_network:
volumes:
  dbdata: # Persistir BBDD
  psdata: # Persistir Prestashop
  psmedia: # Para imágenes
  pstranslations: # Persistir traducciones
  pslogs: # Para logs